quarkus.http.port=8099
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=sa
quarkus.datasource.password=admin
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/product_db

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.swagger-ui.always-include=true
